name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify your Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Install pytest for running tests

      - name: Run Tests
        run: |
          python -m unittest discover  # Run tests using unittest

  deploy:
    runs-on: ubuntu-latest
    needs: test  # This job requires the 'test' job to complete successfully
    if: success()  # Deploy only if the test job succeeded

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Send Message to Operation Team
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Use the secret here
        run: |
          echo "${SSH_PRIVATE_KEY}" > id_rsa
          chmod 600 id_rsa
          ssh -o StrictHostKeyChecking=no -i id_rsa root@flexcd222 "echo 'hi operation team' >> /tmp/op.txt"